use crate::chess_pieces::{GodotPieceColor, GodotPieceKind};

pub const LIGHT_SQUARE_COLOR: &str = "#f4dbc2";
pub const DARK_SQUARE_COLOR: &str = "#bb5746";
pub const SELECT_BORDER_COLOR: &str = "#403e39";
pub const LEGAL_MOVE_HELPER_COLOR: &str = "#00000040"; //"#9e9c9580"
pub const RESOURCES_FOLDER_PATH: &str = "res://resources/";
pub const ENGINE_MOVE_FOLDER_PATH: &str = "./data//moves/";
pub const MOVE_SOUND_FILE_NAME: &str = "move.ogg";
pub const CAPTURE_SOUND_FILE_NAME: &str = "capture.ogg";
pub const SOUNDS_SUBFOLDER_PATH: &str = "sounds/";

pub const START_POSITION: [Option<(GodotPieceColor, GodotPieceKind)>; 64] = [
    Some((GodotPieceColor::Black, GodotPieceKind::Rook)),
    Some((GodotPieceColor::Black, GodotPieceKind::Knight)),
    Some((GodotPieceColor::Black, GodotPieceKind::Bishop)),
    Some((GodotPieceColor::Black, GodotPieceKind::Queen)),
    Some((GodotPieceColor::Black, GodotPieceKind::King)),
    Some((GodotPieceColor::Black, GodotPieceKind::Bishop)),
    Some((GodotPieceColor::Black, GodotPieceKind::Knight)),
    Some((GodotPieceColor::Black, GodotPieceKind::Rook)),
    Some((GodotPieceColor::Black, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::Black, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::Black, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::Black, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::Black, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::Black, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::Black, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::Black, GodotPieceKind::Pawn)),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some((GodotPieceColor::White, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::White, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::White, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::White, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::White, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::White, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::White, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::White, GodotPieceKind::Pawn)),
    Some((GodotPieceColor::White, GodotPieceKind::Rook)),
    Some((GodotPieceColor::White, GodotPieceKind::Knight)),
    Some((GodotPieceColor::White, GodotPieceKind::Bishop)),
    Some((GodotPieceColor::White, GodotPieceKind::Queen)),
    Some((GodotPieceColor::White, GodotPieceKind::King)),
    Some((GodotPieceColor::White, GodotPieceKind::Bishop)),
    Some((GodotPieceColor::White, GodotPieceKind::Knight)),
    Some((GodotPieceColor::White, GodotPieceKind::Rook)),
];
